### ISSUE TITLE
no instructions for starting Python

### ISSUE THREAD

**Issue by janetriley** [swcarpentry/python-novice-inflammation#10]
There are no instructions for how to start Python. We jump right into `import numpy` in section 1.

I could copy  [the instructions from python-novice-turtles](https://github.com/swcarpentry/python-novice-turtles/blob/gh-pages/01-poly.md) .  Thoughts?

**Comment by janetriley** [comment]
@abostroem @tbekolay ,  do you prefer to work with an issue first and then a pull request?  It might be more efficient if I make a pull request and submit an issue alongside it.   We'd have something concrete to respond to.

**Comment by gvwilson** [comment]
So far, people have mostly submitted pull requests as soon as they 
thought they had a fix, and discussion has revolved around those - 
issues are mostly "I noticed this but I don't know what to do about 
it/don't have time to fix it right now".

**Comment by janetriley** [comment]
I'll submit a PR in the next couple nights.  Please feel free to assign this and #9 to me.

**Comment by tbekolay** [comment]
@janetriley, if a PR would be a lot of work and it might be controversial, then I think an issue first makes a lot of sense. If the PR is approximately as much work as making an issue for it, then I say go ahead and make the PR with no associated issue -- the PR acts as the issue in this case, as we can make comments on the PR as we do an issue.

I think the reason we don't talk about how to start Python in this lesson is because in many cases we teach it from the IPython notebook. Of course, that might not always be the case, and since we're no longer including notebooks in the repository, it makes a lot of sense to include something about starting up Python in these materials.

**Comment by alexsavio** [comment]
I am looking for issues where I may be able to help. It would be nice to close the issues that are already solved, otherwise I have to read through all of the open ones.
