### ISSUE TITLE
Missing link/reference on precision in Python - Episode 8: Creating Functions

### ISSUE THREAD

**Issue by jamesacris** [swcarpentry/python-novice-inflammation#1013]
In the [Testing & Documenting](https://swcarpentry.github.io/python-novice-inflammation/08-func/index.html#testing-and-documenting) section of episode 8, there is an allusion to the precision of some data types in Python, when testing the `offset_mean` function:

> The mean of the offset data isn’t quite zero — we’ll explore why not in the challenges — but it’s pretty close.

As far as I can tell, there isn't any other mention of what this sentence is alluding to anywhere in the lesson notes. I could just be missing something, in which case I'd be happy to be pointed in the right direction (though I might suggest adding a link to this section so people aren't left wondering where it is like I was!).

If I'm not missing something and this actually isn't followed up on in the notes, we should consider adding an exercise or add to the notes to explore this further.

**Comment by JamesAllsopp** [comment]
This is a numerical precision thing for floating point numbers. I think this is appropriate as talking about floating point numbers being an approximation to reality is going to massively add cognitive load and complicate things. This is where footnotes would be really useful.

**Comment by tobyhodges** [comment]
A community member contacted The Carpentries because they were confused by this section. It seems that changes to NumPy (and the increase in memory available on a typical computer) have rendered this comment in the lesson unnecessary. I tried the example code (I've commented out the non-essential print statements below), and got a difference of zero:

```python
import numpy

data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

def offset_mean(data, target_mean_value):
    return (data - numpy.mean(data)) + target_mean_value

# print('original min, mean, and max are:', numpy.amin(data), numpy.mean(data), numpy.amax(data))

offset_data = offset_mean(data, 0)

# print('min, mean, and max of offset data are:',
#       numpy.amin(offset_data),
#       numpy.mean(offset_data),
#       numpy.amax(offset_data))

# print('std dev before and after:', numpy.std(data), numpy.std(offset_data))

print('difference in standard deviations before and after:',
      numpy.std(data) - numpy.std(offset_data))
```

```output
difference in standard deviations before and after: 0.0
```

(Python version 3.9.7; NumPy version 1.20.3 - so not new, exactly, but relatively up-to-date)

To me, it looks like this section needs to be updated, which would also have the effect of removing the source of confusion reported by @jamesacris above. Could one of the @swcarpentry/python-novice-inflammation-maintainers try this out on their system, please, and let me know if they see the same? If so, I would be happy to submit a PR to update the episode content.

**Comment by noatgnu** [comment]
@tobyhodges  I have tried this on Python 3.11.3 and the result seems to be the same with the minus operation giving a `0.0` result and the evaluation of whether that value and `0` is the same also giving a `True` output. So I imagine that this should be updated.
