### ISSUE TITLE
Python modules: hyphens to underscores

### ISSUE THREAD

**Issue by dotsdl** [swcarpentry/python-novice-inflammation#152]
Many of the python modules in [``code``](https://github.com/swcarpentry/python-novice-inflammation/tree/gh-pages/code) include hyphens in the name, making them practically impossible for learners to import (there is a way, but it's really obtuse and bad form). These should be changed to e.g. underscores in order to make them easily importable.

**Comment by hachterberg** [comment]
Since it seems this issue is still open, I heartily agree with this. The not being able to import is inconvenient, but also it is against the python conventions.

According to PEP8 (which I think should be encouraged as much as possible) modules should be all lower case letter, and underscores can be used if it improves readability (see [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)). 

If the mainters agree with this, I don't mind doing the actual changes and sending a pull request.

**Comment by tbekolay** [comment]
I suggested this in #172, so I'm definitely in favor of changing them to underscores :)

**Comment by hachterberg** [comment]
Great, @tbekolay are there any specific references to the code that need to be changed. I couldn't find them quickly, and "make preview' seemed unaffected. Should I just go ahead and make a pull request?

I could not run "make unittest" because of a problem with changes in CommonMark, but requirements.txt not specifying a working version of CommonMark.

**Comment by tbekolay** [comment]
Both `make preview` and `make unittest` are only things that maintainers need to worry about; for the PR, only touch the `.py` and `.md` files. There are references to the `readings` files in `instructors.md` and `10-cmdline.md`. I think that's it though :)

**Comment by dotsdl** [comment]
I should have been more specific: the issue I had here was with [errors_01.py](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/code/errors_01.py) and [errors_02.py](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/code/errors_02.py), which as of f876f3b946ef1ddf10c46b50e2d7ccdf19f77542 were switched from having dashes to underscores. This was important because in the [lesson itself](http://swcarpentry.github.io/python-novice-inflammation/07-errors.html) learners are asked to import these modules. Before with the dashes they would have been unable to do so.

I don't mind that the scripts that are not intended to double as modules have hyphens (though I don't really see the point of making them unimportable, as argued by @iglpdc and @ctb), so I'm going to close this. If others think we need to make all scripts importable (I'm in support, but don't mind either way), then we can re-open.
