### ISSUE TITLE
DataFrames instead of numpy arrays?

### ISSUE THREAD

**Issue by djinnome** [swcarpentry/python-novice-inflammation#342]
Hi folks,

  One of the challenging and frustrating things about working with multi-dimensional data is keeping track of indices.  Was the patient the rows or the columns?  Do you index row, column, or column, row?
For folks who are used to working with Excel files, working with arrays must feel like a giant step backwards.  On the other hand, DataFrames are much better suited to handling data files with labeled columns and rows, and can do things with data that even advanced Excel users can't do...

I am considering whether to refactor the existing episodes to use DataFrames rather than numpy arrays, and was wondering if there is any interest from the community in this contribution?

**Comment by tbekolay** [comment]
Hi @djinnome, thanks for your interest in the lesson! Indeed this is a common piece of feedback we get. So common that @gvwilson made a new Python lesson from scratch that uses DataFrames rather than numpy arrays; see [python-novice-gapminder](http://swcarpentry.github.io/python-novice-gapminder/).

Since that lesson exists, I think effort taken to revamp this lesson would be better spent improving the gapminder lesson. Though, if you want to fork this lesson and make a DataFrame version, definitely feel free! But I don't think we'll ever switch over in this lesson; there's some value to having one lesson using NumPy and one lesson using DataFrames.

**Comment by djinnome** [comment]
Hi @tbekolay thanks for pointing me to the gapminder lesson, and thanks @gvwilson for creating it!  I will definitely look it over and see if I can contribute something useful to it.
