### ISSUE TITLE
Lesson 01-numpy requires matplotlib

### ISSUE THREAD

**Issue by agbeltran** [swcarpentry/python-novice-inflammation#401]
The lesson [01-numpy](http://swcarpentry.github.io/python-novice-inflammation/01-numpy/) requires the installation of ```matplotlib``` and this installation is not done in the [setup](http://swcarpentry.github.io/python-novice-inflammation/setup/)

**Comment by tbekolay** [comment]
Hm, I think there was some discussion about this at some point, but the instruction to install Python and various libraries were kept out of this repository because there are other Python lessons, and it would be a pain to update the installation instructions on all Python lessons whenever a change is made. Because of that, we instead opted to link [these instructions](http://swcarpentry.github.io/workshop-template/#setup), which go over installing Anaconda, which installs `matplotlib` by default.

This all said, it is not super clear that we expect those instructions to be followed before starting the lesson. PRs welcome!

**Comment by agbeltran** [comment]
OK, thanks for clarifying. I now see that the [setup](http://swcarpentry.github.io/python-novice-inflammation/setup/) does point to the [instructions you mentioned](http://swcarpentry.github.io/workshop-template/#setup) and indicates that people should have already installed Anaconda.

I think it might be useful to add a little note pointing to this (and referring to how to install ```matplotlib``` with ```pip install```) when the library is first used - so I will leave this issue open and send a PR with this note.

Thanks!
