### ISSUE TITLE
Consistency in 02-loop lesson

### ISSUE THREAD

**Issue by nmearl** [swcarpentry/python-novice-inflammation#408]
The pacing and introduction of python concepts centered around the 02-loop lesson, seems a bit jarring and inconsistent:

- The beginning of the lesson establishes loops as an easy way to repeat operations, _specifically_ creating plots for sets of data, but this is not done in the lesson.
- The lesson involves using lists as an example of other iterables with which `for` can be used; however, lists have not been introduced to the learner until the following lesson.
- Variable scoping is introduced, but not expanded on, and no previous lesson seems to tackle the idea of namespace/local scopes within python.

Just wanted to point this out for discussion, and if there's interest, I can try opening a PR with my envisioned flow.

**Comment by smangham** [comment]
I'd definitely agree with this. Given the previous step was very practically-oriented and quite detailed, the switch to a more abstract, theoretical (and notably easier!) style is a bit jarring. 

The 'drawing straight lines' section of code from the previous lesson could easily be dropped into a for loop over an list of filenames (maybe saving the figures instead of plotting them). This would clash with the explanation of lists in the next section, but then we've already explained numpy arrays in the first lesson!

**Comment by jag1g13** [comment]
Since Numpy has been brought up in the previous session, why not have a loop over a Numpy array as one of the examples?  That would also partially address the first point - that we explicitly point out iterating over multiple datasets as the example for where loops are useful, but don't do that until later.

In my (very brief, I have taught this session only once) experience this section on loops is much less demanding that the previous session where we cover quite a quick ramp from variables to array manipulation.  Including some array manipulation in this section may help to reinforce the previous lesson.
