### ISSUE TITLE
New default colormap for matplotlib

### ISSUE THREAD

**Issue by wyojustin** [swcarpentry/python-novice-inflammation#428]
The colormap for matplotlib2.0 has changed from "jet" to "viridis".  Please [see](https://matplotlib.org/users/dflt_style_changes.html#colormap) for a description and justification.  Having attended scipy when this issue was vigorously debated, I know many people to not take this issue lightly.

I suggest the following enhancement: replace fig/01-numpy_71_0.png with an updated plot.  Happy to submit PR.

![image](https://user-images.githubusercontent.com/905307/32667703-6ef6ede4-c609-11e7-957b-6ee999abc77b.png)

**Comment by daguiam** [comment]
I also agree with changing the image in the online lessons to the new default colormap `viridis`.

Since this is a novice python class, most students will be installing python for the first time, which results in most students having matplotlib2.0 installed.
As the instructor giving the class may also have the latest matplotlib version installed, the plots they show when live coding will also have the new `viridis` colormap, matching the students'.

However, many people use the online lessons to learn from home. Having different colormap for the lesson plan and the student's plot may raise some unnecessary questions for the first section of the python lesson.
