### ISSUE TITLE
Point to code location in "Errors and exceptions"

### ISSUE THREAD

**Issue by zonca** [swcarpentry/python-novice-inflammation#51]
The `errors_01.py` and `errors_02.py` modules for the lesson on "Errors and exceptions" are available in the `code/` folder:

https://github.com/swcarpentry/python-novice-inflammation/blob/d79d0440540a30d7e839f82e370412e595e3549d/code/errors-01.py

We might point to them in the lesson so people can find them.

**Comment by jesford** [comment]
The same is true for the `readings*.py` files and `count_stdin.py` and others in "Debugging" and "Command-line Programs" lessons... and it took me a little while to locate them.

Are these programs intended to be run by students during the workshops? If so, I think they should be included in the `python-novice-inflammation-data.zip` file that the students download. If not, it would be nice if they were easier for instructors to find (maybe a separate zip file in the lesson?).

**Comment by Ry4an** [comment]
I'm calling dibs on this one.

**Comment by jesford** [comment]
Thanks for taking this on @Ry4an.

I wonder whether its worth having `errors_01` and  `errors_02` in files at all...  they are such short code snippets anyway that the overhead of making sure every student has them downloaded and somewhere in their path might not be worth it. When I taught this lesson I ended up just having students type them into a notebook cell, which I think saved time because it was easier to quickly understand the code and edit to resolve the errors. I believe this section is the first and only time that they import something other than a standard package like numpy, so thats another cognitive load consideration as well.

Regarding the `readings*.py` files on the other hand, I think it would be good to have these in an easy-to-find and download location. To me, the lesson was really unclear on whether I (as the instructor) was supposed to have students download and run each of these (thats what seemed to be implied), or if I was to lead them through building up these files by writing them (which seemed better for learning, but then why are there so many versions of the same file?). TL;DR - the text of this lesson needs improving to make it clear what to do with the `readings*.py` programs.

**Comment by Ry4an** [comment]
@jesford I think you're right about those errors.  I'll see if they can be inlined without becoming confusing.

I'll check into the readings*.py bit to see if I can find something non-awful to do with that too.

**Comment by valentina-s** [comment]
@Ry4an I think it is a good idea to put the code in a `python-novice-inflammation-code.zip`. Often a one-day workshop does not reach this lesson so then they can download the data without downloading the code as they will not use it. I just merged a pull request fixing the paths to the files in cmdline #258. I still think we need explanation from where to run the files from (as suggested here #89).

**Comment by Ry4an** [comment]
@valentina-s I put up a PR (#272) including the buggy code inline since @jesford suggested it's nice when the users can copy/paste it into a console and see the errors themselves.

No hard feelings if you feel it's too much to in the lesson itself.

**Comment by Ry4an** [comment]
Yeah, I can find a place for it in gap minder, but there's a vote in the PR (#272) about the approach that still feels below quorum. Mind weighing in?

**Comment by Ry4an** [comment]
> Can this be moved to the new python-novice-gapminder lesson? paging @Ry4an ...

I just updated PR #272 with all the input there.  If that looks like folks want it to I'll do a similar PR into gapminder.

**Comment by valentina-s** [comment]
This has been resolved. I added an issue to the gapminder lesson to see if they would like such a change: https://github.com/swcarpentry/python-novice-gapminder/issues/247
