### ISSUE TITLE
Use numpy when calculating the mean for consitancy

### ISSUE THREAD

**Issue by Sabryr** [swcarpentry/python-novice-inflammation#597]
In: https://swcarpentry.github.io/python-novice-inflammation/04-files/index.html

The example plot is made by calculating max, min and average using numpy. However the when providing the solution to the question, numpy not used,
i.e.
matplotlib.pyplot.plot(data0.mean(axis=0) - data1.mean(axis=0))

I would suggest to use 
matplotlib.pyplot.plot(numpy.mean(data0, axis=0) - numpy.mean(data1 ,axis=0))
instead 

This would not only make it consistence there will be a performance increase for larger data-sets (depending how numpy was compiled of course). 

I will submit a PR in a moment to explain what I mean.

**Comment by Sabryr** [comment]
>>> data0 = numpy.loadtxt(fname=filenames[0], delimiter=',')
>>> type(data0)
<class 'numpy.ndarray'>

**Comment by annefou** [comment]
The change you suggest makes it more consistent with the rest of the lesson but invoking performance reasons can be misleading for novices. My opinion (based on experience) is that whenever you invoke performance to novice users take it for granted and apply any mis-understood recipes to anything (for instance using numpy.mean on a dask array).

**Comment by maxim-belkin** [comment]
@Sabryr, please look closely at the output you see in https://github.com/swcarpentry/python-novice-inflammation/issues/597#issuecomment-436061133
`data0` (and `data1`)  **are** numpy array(s) and performance **is not** affected in any way.
You change is, however, still acceptable because this is what was decided upon previously, see Frequently Asked Issues here: https://swcarpentry.github.io/python-novice-inflammation/guide
