### ISSUE TITLE
Lesson 3 - del function

### ISSUE THREAD

**Issue by HeatherAn** [swcarpentry/python-novice-inflammation#669]
In lesson 3, when referring to 'Heterogeneous Lists' the function del is used to delete the first element of the 'odds' list. In the lesson, it appears as 'del odds[0]', which is ok. However during the lessons we have used the functions with the parenthesis, so it might be a bit confusing for the student to see that del is used with a space, while almost all the other functions are used with parenthesis. Thus I would suggest, to either use 'del(odds[0])' or explain why 'del odds[0]' also works.

**Comment by ldko** [comment]
Hi @HeatherAn,  [`del`](https://docs.python.org/3/tutorial/datastructures.html#the-del-statement) is a statement in Python, not a function, so using it is different than calling a function. I think `del(odds[0])`  works not as calling a function but as doing `del odds[0]` where odds[0] happens to have parentheses around it that are basically ignored. I do think the idea of statements vs. functions/methods is confusing as is switching between them in the examples like you mention. I wonder if it would make sense to change `del odds[0]` to `odds.pop(0)` for consistency with the examples around it.

**Comment by HeatherAn** [comment]
Good one! I did not know it was a statement, I always thought it was a function since I have always used it in parenthesis. Interesting. I would still suggest to use the notation in parenthesis to be consistent with the rest of the lesson. Also because the lessons are not that specific in terms of what is what (e.g., the difference between a method and a function is not mentioned; statements are not mentioned; difference between libraries and modules is not clearly mentioned).

**Comment by maxim-belkin** [comment]
The reason `del(odds[0])` works is a combination of several factors.

1. `del` can delete several variables at once if they're separated with a comma: `del a, b`.

1. Whenever Python expects a bunch of things (things separated with commas), it interprets them as a tuple (unchangeable list) and _unpacks it when necessary_. That's why we can do things like
    ```
    a, b = c, d
    a, b = (c, d)
    a, b = ((((c, d)))) # any number of matching `()` will work
    a, b = [c, d] # only one level of matching `[]` will work
    (a, b) = c, d
    (((a, b))) = (c, d)
    (a, b) = [c, d]
    [a, b] = c, d
    [a, b] = (c, d)
    [a, b] = [c, d]
    ```
    as well as
    ```
    a = (b)
    (a) = (b)
    (((a))) = (b)
    ```

    Parentheses and square brackets are not treated equally: one can do `a = ((((b))))` or `(((a))) = b` instead of `a = b` but this is different from `a = [[[[b]]]]` and `[[[a]]] = b` is not allowed.

3. Python doesn't care about spaces much<sup>*</sup> (as long as they're not in the beginning of lines and inside of strings). That's why we can `print(1)`, `print    (1)`.

So, when Python sees `del(a[0])` it decodes it in the following manner:
```
del(a[0]) --> del (a[0]) --> del a[0]
```

So, even though `del(a[0])` does look like a function, it is not and there is a HUGE difference between a statement and a function. Mainly, statements do not return a result (they _do_ things) and their behavior can not be changed with options. Example: you can do `a = print(1)` (`a` will be `None`), but you can't do `b = del some_variable` (you'll get an error).

So, given all of that, I'd like to argue with your statement:

> I would still suggest to use the notation in parenthesis to be consistent with the rest of the lesson.

on the grounds that there shouldn't be "consistency" in this question. 

You then say:

> the lessons are not that specific in terms of what is what (e.g., the difference between a method and a function is not mentioned; statements are not mentioned; difference between libraries and modules is not clearly mentioned).

We do define methods in `reference.md` and link to it from the first episode. We do mention several different statements (`if`, `return`) without putting too much emphasis on it. And... libraries and modules are the same thing (in Python), so I'm not sure about that point.

**Comment by ldko** [comment]
I think @HeatherAn does make a valid point with her initial issue here that the syntax of `del odds[0]` positioned in between examples of `odds.append(11)` and `odds.reverse()` without an explanation of the syntax difference is confusing. @maxim-belkin  What do you think about using `odds.pop(0)` in place of  `del odds[0]` or including a brief note of some sort about why 'del odds[0]' works/has a different syntax?

**Comment by maxim-belkin** [comment]
> I think @HeatherAn does make a valid point with her initial issue here that the syntax of `del odds[0]` positioned in between examples of `odds.append(11)` and `odds.reverse()` without an explanation of the syntax difference is confusing.

I agree that the place where we describe `del` is weird. Moreover, this is the only place where we use/mention `del` statement. So, the real question is... do we need it? I want to say "yes" because we show how to `.append` elements to a list, so it makes sense to also show how to remove elements.

> What do you think about using `odds.pop(0)` in place of `del odds[0]` or including a brief note of some sort about why 'del odds[0]' works/has a different syntax?

`.pop()` returns the element it "pops" and, therefore is useful for processing lists with `while` loops (`a = list(range(10)); while a: print(a.pop(-1))`). Of course, `.pop()` achieves the same effect as `del` if the value it returns is discarded but this is a "by-product".

**Comment by ldko** [comment]
I agree it makes sense to show how to remove elements.

If you want to avoid a "by-product" it could be something like:
```
odds = [1,3,5,7]
removed_element = odds.pop(0)
print('After removing', removed_element, 'odds is', odds)
```
```
After removing 1 odds is [3, 5, 7]
```
Which would show not only how to take an element out of the list but that you could actually use the removed value--which some might find to be practical information (even if not tying it into processing a list with a loop).

If you prefer `del` than perhaps we could include an acknowledgment about why the `del` syntax is different.

**Comment by maxim-belkin** [comment]
I like your example, @ldko. Can you submit a PR with it?

A part of me wants `del` to be mentioned in the lesson, but given how infrequently I use it myself, I'm OK with removing it. What do you think, @annefou?

**Comment by maxim-belkin** [comment]
Thank you both @HeatherAn and @ldko! 🌷
