### ISSUE TITLE
Lesson 6 - triple quotes

### ISSUE THREAD

**Issue by HeatherAn** [swcarpentry/python-novice-inflammation#672]
In Lesson 3, in the 'Testing and Documenting' section, it refers to docstrings. It says 'we don't need to use triple quotes when we write one, but if we do, we can break the string across multiple lines'. It would be good to add here that if we use triple quotes within a function, then that text shows up when calling help (the text does not show up when using help() if we use '#' to write a comment). This is written below as code, but it is not explicitly mentioned.

**Comment by maxim-belkin** [comment]
Good suggestion, @HeatherAn! Would you be willing to submit a pull request?

**Comment by maxim-belkin** [comment]
Hi Heather. The lesson currently has the following wording:

> If the first thing in a function is a string that isn’t assigned to a variable, that string is attached to the function as its documentation:...
... This is better because we can now ask Python’s built-in help system to show us the documentation for the function:

I think it covers what you added in #672. Nonetheless, thank you for taking the time to submit this issue and create #672! 🥇
