### ISSUE TITLE
Lesson 10 - numpy.mean(data) and data.mean

### ISSUE THREAD

**Issue by HeatherAn** [swcarpentry/python-novice-inflammation#675]
In lesson 10, when the lesson refers to readings_03.py, the code shows that to calculate the mean over 'data' across all days, numpy.mean is used: numpy.mean(data, axis=1). However when looking at the file readings_03.py (at least the version I downloaded recently) uses the instruction  data.mean(axis=1). Both lead to the same result, but for consistency I would suggest to either  modify the readings_*.py to use numpy.mean (as this is what it has been used throughout the entire lesson), or explain explicitly that both expressions lead to the same result (it would be a good time to remind students about object attributes).

**Comment by maxim-belkin** [comment]
Thank you, @HeatherAn! A while back, The Council of the Wise of this lesson decided that it is preferable to teach functions over methods (where it makes sense to do so), see #244.
This means that we should use `numpy.something(data, ...)` instead of `data.something(...)` .
Please feel free to submit a pull request to fix `readings_03.py`.
