### ISSUE TITLE
Adding PDB to the debug lesson

### ISSUE THREAD

**Issue by nbrinckm** [swcarpentry/python-novice-inflammation#789]
Hi folks,

I wonder if it is useful for the debugging lesson in the python novice workshop to let the people know that they can import the python debugger as any other module and make calls on `pdb.set_trace()` and can try to inspect their variables on the go.

So if we look at the last task in the lesson with the BMI they can change to code to something like this:

```python
import pdb

patients = [[170, 1.8], [80, 1.9], [150, 1.7]]

def calculate_bmi(weight, height):
    return weight / (height ** 2)

for patient in patients:
    weight, height = patients[0]
    pdb.set_trace()
    bmi = calculate_bmi(weight, height)
    print("Patient's BMI is: %f" % bmi)
```

So executing the code, the learners then are in the python debugger session, so that they can print out the variables in the first run:

`weight, height`

and see that they match was they expect. Then we use the `c` pdb command to continue and are in the second run of the loop, so they can inspect the variables again:

`weight, height`

and see that they are still the very same ones as before, but not the ones of the current patient.

---------------------

I know that this introduces a lot of new complexity, but it may be a good starting point for the debugging knowledge for the learners. For me the possibility to use the debugger in this module like way is something I do over and over again and that I miss in other languages that don't support jumping in the debugger from within the running program.

However as I'm currently working mostly with scripts and not with Jupyter notebooks, I'm not sure whether this works using notebooks.

**Comment by ldko** [comment]
Hi Nils, thank you for opening this issue to suggest the use of `pdb` in the debugging episode. With the title of the episode being "Debugging", it seems like it would make sense to mention `pdb`.  Also, `pdb` does work using notebooks. However, as you say, this does introduce a lot of new complexity. I think there would be a small percentage of learners that would be excited about seeing this addition, particularly if they have a fair amount of programming experience and understand how to debug and the concept of debuggers. For most though, I think the explanation of what a debugger does, what `set_trace` does, and the need to explain how to interact with the debugger with commands like `continue` may be too much not only for the learner but also for some instructors based on this lesson already being over full for the time constraints of a workshop. What do you think about it @annefou @maxim-belkin ?

**Comment by nbrinckm** [comment]
The complexity is in issue for sure (and being in time for the instructures is another very important point that I totally missed in my suggestion).

However, sometimes it may make sense to just give the pointer on where to look for additional stuff. Debugging and the pdb are important and it really makes sense if the people are getting used to it.
I can see that this may be an more advanced topic (in #127 I saw the discussion about mention it for the  "Some Previous Programming" audience), but currently I see no real other place where to put it in as the python intermediate workshop is in a state barely about non existing.

Adding the PDB at least at the end of the debugging section would allow the instructors to point to it, to allow some live coding (I haven't seen a part in there where it really makes sense at the moment) and we may have a chance that people reach a level of not using print statements alone as their debugging strategy as they know that there is some better tool (and included in the python standard library). For something like Smalltalk dialects interactive debugging is a killer feature. PDB is not that powerful but its way more pleasant compared to debugging in C/C++.

Anyway I see the pdb as an optional part at the end of the debugging session so that people can use it if there have some time left. And as I'm barely in expert regarding teaching, so I can't really estimate how people will react on the additional complexity here.

**Comment by ldko** [comment]
The lesson does have an extras section for [additional material](http://swcarpentry.github.io/python-novice-inflammation/extra_material/) that I think it would be nice if we generally made more use of. Perhaps putting information and an example about using `pdb` would make sense in here? @maxim-belkin @annefou do you have opinions about what should or should not go into the additional material section?

Another place `pdb` could go if people want it in the debugging episode directly  would be a short callout box similar to the one that mentions [`argparse` in the command-line](https://github.com/swcarpentry/python-novice-inflammation/blob/264020e06f47cb557680a1a63e2bcfd73ee7f696/_episodes/12-cmdline.md#the-right-way-to-do-it) episode. It frequently comes up that we should teach `argparse` because it is more realistic to real use, however, the time it takes to teach what we are with command-line arguments using `argparse` has been determined not to fit into the time (I was initially one of the we-should-teach-argparse people until I tried translating what is in the episode to use `argparse` and seeing the amount of code and needs for explanation made me realize why we don't teach it).

**Comment by maxim-belkin** [comment]
The question of whether this lesson should cover `pdb` is a very interesting question.

In general:

1. modules like `subprocess`, `re`, `pathlib`, `argparse`, `pdb`, (maybe `os` and `sys` too)  and others deserve their own "intermediate" python for researchers lesson.
2. `pdb` module becomes necessary when
   - one transitions to writing complex functions that are difficult to "debug" with `print` statements.
   - when each iteration of a function takes a while and it becomes impractical to keep running it with new `print` statements many times.
3. To properly teach `pdb` module , we have to teach its terminology and core concepts (stack, (stack) trace, (stack) frame, traceback, breakpoint, jumps, command aliases (because c == cont == continue)). If we don't explain these concents, learners will have no choice but to (try to) remember the functions (`pdb.set_trace`) we use.

Yet, I agree with the idea to point people in the right direction, similarly to what we do with `argparse`. Perhaps, we could give an example on how the same bug-hunting procedure will look like with `pdb`. It can be a callout box or a "challenge" in the debugging episode or a section in an episode in `_extras`.

**Comment by ldko** [comment]
@nbrinckm , we appreciate the time you spent on this issue. After discussing adding `pdb` to the lesson at our maintainers call this week, we decided that it would not currently fit into the lesson based on reasons including:
* We are assuming an audience of novice programmers, many of whom don't have experience with other languages and what they offer in the form of debugging.
* The functions we are writing in this introductory lesson are not complex, so debugging via `print` should be sufficient.
* Teaching `pdb` would require several minutes to give a sense of how a debugger works, concepts (e. g. breakpoints, stack frame), and commands to work with it. Without removing other material to allow teaching time for this, it is difficult to justify.
