### ISSUE TITLE
Episode 5 - Unnecessary cultural reference?

### ISSUE THREAD

**Issue by neil-csiro** [swcarpentry/python-novice-inflammation#801]
In instructor training we were taught that we should avoid culture-specific references in our teaching.  I took this as being about old favourites like "foo bar", and references to literature like Monty Python, Hitchhikers Guide to the Galaxy and Lord of the Rings.

But would "Ch-Ch-Ch-Ch-Changes" (being the title of a subsection of the episode), be relevant to this too?  I recognise the David Bowie reference, but is this unnecessary and perhaps just slightly hostile to folk who aren't familiar with this cultural reference?

If so, I'll make the minor edit to remove this and PR.  Apologies if this seems to be taking concern for cultural references too far.

**Comment by ldko** [comment]
Hi @neil-csiro, thanks for bringing up your concern. I would say the "Ch-Ch-Ch-Ch-Changes" title is not necessary to retain if it may be seen as culture-specific, though I wouldn't classify it as hostile. I don't think being unfamiliar with the reference in this case impacts a learners ability to understand nor distracts from the material there. If you would like to remove the reference, perhaps renaming the section something like "Mutable Versus Immutable" would be sufficient.

**Comment by neil-csiro** [comment]
Thanks - I'll make this change and PR in the next few days.

**Comment by maxim-belkin** [comment]
Hi @neil-csiro. Before you put together a PR, let me clarify your motivation: does this reference offends you personally or are you following the guidelines taught in the instructor training? I'm asking this because there is a big difference between these two scenarios. If this reference does not offend you personally, I'd be inclined to keep it in because teaching cannot happen in vacuum and new material has a better chance of sticking in learners' heads if we give it something more than a plain logic to grab on.

Thanks for your understanding and multiple contributions!

**Comment by neil-csiro** [comment]
Hi @maxim-belkin, this doesn't offend me personally - I was trying to apply the guidelines in instructor training.  I'm a fan of the performer being referenced.

**Comment by ldko** [comment]
Based on the response from @neil-csiro and @maxim-belkin , I am going to close this issue. If anyone has further concerns regarding the issue, we can reopen at that time.

**Comment by maxim-belkin** [comment]
Thanks, @neil-csiro.
Thanks, Lauren.
