### ISSUE TITLE
03-matplotlib, use matplotlib.pyplot.subplots instead of  matplotlib.pyplot.figure

### ISSUE THREAD

**Issue by jdkent** [swcarpentry/python-novice-inflammation#821]
in the grouping plots section, users are introduced to [`matplotlib.pyplot.figure`](https://github.com/swcarpentry/python-novice-inflammation/blob/0cc4282978311d9267a96095a17fd9141177c3e8/_episodes/03-matplotlib.md#grouping-plots), and add three subplots to the figure, like so:

```python
import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

fig = matplotlib.pyplot.figure(figsize=(10.0, 3.0))

axes1 = fig.add_subplot(1, 3, 1)
axes2 = fig.add_subplot(1, 3, 2)
axes3 = fig.add_subplot(1, 3, 3)

axes1.set_ylabel('average')
axes1.plot(numpy.mean(data, axis=0))

axes2.set_ylabel('max')
axes2.plot(numpy.max(data, axis=0))

axes3.set_ylabel('min')
axes3.plot(numpy.min(data, axis=0))

fig.tight_layout()

matplotlib.pyplot.show()
```

I find that specifying there are 3 subplots to enter for every call of `add_subplot` a little confusing and different from how I interact with `matplotlib`. I use `matplotlib.pyplot.subplots` which handles the use case of having only one axis on a figure to having as many axes as you would like.
So the resulting example would look like this instead:

```python
import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

fig, axs = matplotlib.pyplot.subplots(nrows=1, ncols=3, figsize=(10.0, 3.0))

axs[0].set_ylabel('average')
axs[0].plot(numpy.mean(data, axis=0))

axs[1].set_ylabel('max')
axs[1].plot(numpy.max(data, axis=0))

axs[2].set_ylabel('min')
axs[2].plot(numpy.min(data, axis=0))

fig.tight_layout()

matplotlib.pyplot.show()
```

### Benefits

- fewer lines of code and fewer variables to keep track of (encouraging generally good programming practices, while still maintaining clarity)
- only have to specify the number of "subplots" once (more intuitive, imo)
- meshes with how _I_ use `matplotlib` in the wild, I want to open this issue to see if this is how others interact with matplotlib as well
- others???

### Cons

- introduces the concept of a list before the proper episode (05).
-  may blend the concepts of creating a figure and axes separately
- others???

Changing this would impact the episode in multiple locations; so I would like further discussion before putting effort towards a pull request.

**Comment by ldko** [comment]
Hi James, thanks for opening this issue that clearly provides reasoning for and against possibly using `matplotlib.pyplots.subplots` in place of `matplotlib.pyplot.figure`. As far as my opinion goes on the matter, while I do think that specifying 3 `ncols` for each call of `fig.add_subplot` seems a bit redundant, I think the text that precedes the code explains it well. Since many of the learners for the python-novice-inflammation material are new to programming and, as you mention, lists are not taught until a later episode, I think this quirk may still be more clear to teach at this point of the lesson. `matplotlib.pyplot.subplots` returning both a figure and what may be either a single Axes object or an array of them may be confusing to see early on in the lesson and be harder to explain than needing to specify `ncols` multiple times. In order to work with people new to programming in the lesson, we are sometimes teaching code that may not be the most used practice for more seasoned programmers, but we can be somewhat limited by what concepts we have available at a particular point in the lesson.

**Comment by jdkent** [comment]
Thanks @ldko for your thoughtful response, I agree you have to make best with tools you have at that particular point, and that the way it is being taught is not the end point for learner, but a stepping stone to learn the material at hand.

I could see an argument for moving the 05 list lesson earlier (since array indexing is taught in episode 02, and lists are a similar concept), but that would also require require a major rewrite of the episodes, is outside the scope of this issue, and does not fix this point you brought up:
> returning both a figure and what may be either a single Axes object or an array of them may be confusing to see early on in the lesson and be harder to explain than needing to specify ncols multiple times

So in the end, using subplots does not appear worth it, but I would still like to have this issue open (for a week?) to see if anyone else wants to put in their two cents.

Thanks again for your response!

**Comment by jdkent** [comment]
This is bit tongue in cheek, looks like I'm suggesting "lawful good" and the lesson is currently "neutral good", so not a major difference according to whoever made this.

![fig](https://pbs.twimg.com/media/EXGYtCbU0AEErHm?format=png&name=large)

credit: https://twitter.com/abhisheksh_98/status/1256953937766174721?s=20

**Comment by maxim-belkin** [comment]
Hi James,

"Don't believe everything you read on the internet" - A. Lincoln. :)

While I agree with what you said about repetitive calls to `add_subplot`, I have to say that repetition is, in a sense, a necessary part of learning. The number of lines of code is, in turn, closely connected to the repetition comment. And, as Lauren has already pointed out, real-world usage is not exactly our goal... though we don't want to be too far away from it. All of these concerns are valid if you know a thing or two about programming in general and Python/matplotlib in particular.

Now, all of that does not mean that this episode is ideal. In fact, there are quite a few problems:

- what is a figure? a subplot? axes? is there an axis?
- why do we name our variables `axes*` when we call `.add_subplot` method? Shouldn't we call them `subplot*`?
- why is it called _subplot_ and not _subfigure_?
- what is the relationship between axes and subplots? do they mean the same thing or are they related to each other somehow? can one of these own two or more of the other?
- Why does `fig.tight_layout()` changes `axes*` and not the figure itself?
- is axis in `axis=0` related to any of the `axes*` variables?
- Can I add legend / title / etc? If so - how?

I think you get the point. Because this episode does not provide answers to the above questions, there is a very high cognitive load on the learners who have to memorize all these `.figure`, `.add_subplot`, `.set_ylabel`, ... methods. To me it is clear that the episode has to be improved, reworked, and perhaps even split into two... And when someone finds the time to do that -- we can definitely consider changing this part of the episode as well.  But until then, I think it makes sense to keep teaching `pyplot.figure` with repetitive `add_subplot`s.

Maxim

**Comment by jdkent** [comment]
Thank you for thoughtful responses to this issue!
I'm unsure if anyone else will comment so I am fine with either leaving this issue open for posterity or closing it to reduce clutter.
