### ISSUE TITLE
Making choices - Add explanation of all comparison operators

### ISSUE THREAD

**Issue by jakekara** [swcarpentry/python-novice-inflammation#853]
In the SWC > Programming With Python > Making Choices Lesson (https://swcarpentry.github.io/python-novice-inflammation/), there is no explanation of the "<=" operator, which is included in the solution to the challenge where students are asked to determine if a is within 10% of b.

This lesson explains the == operator, but it might also be a good lesson to introduce all of the comparison operators (https://docs.python.org/3/reference/expressions.html#value-comparisons).

We already have this example:

```
num = -3

if num > 0:
    print(num, 'is positive')
elif num == 0:
    print(num, 'is zero')
else:
    print(num, 'is negative')
```

Perhaps something like this would be a good follow-on in the same style.

```
num = 0
if num >= 0:
   print(num, "is not negative")
if num <= 0:
   print(num, "is not positive")
```

**Comment by ldko** [comment]
Hi Jake,
You have made a good point about the lack of explanation of different operators available for value comparisons in the [Making Choices](https://swcarpentry.github.io/python-novice-inflammation/07-cond/index.html) episode.

Perhaps we could add a sentence (or a callout box) after the sentence "Note that to test for equality we use a double equals sign == rather than a single equals sign = which is used to assign values" such as:
In addition to the `>` and `==` operators we have seen so far, other operators available for comparing the values of two objects include `<` (less than), `<=` (less than or equal), `>=` (greater than or equal), and `!=` (not equal).

We could then add your suggested example or perhaps change this example (rather than add another example which would add more time to teaching the episode):
```
if (1 < 0) or (-1 < 0):
    print('at least one test is true')
```
to
```
if (1 < 0) or (1 >= 0):
    print('at least one test is true')
```
What do you think @maxim-belkin ?

Thanks for opening this issue and contributing to the lesson, Jake!

**Comment by maxim-belkin** [comment]
> What do you think @maxim-belkin ?

Thanks for pinging me, Lauren. I think this would be a very fine addition to the lesson, especially for operators made of two symbols (`==`, `!=`, `>=`, and `<=`).

Thank you, Jake, for the suggestion!

**Comment by stefpiatek** [comment]
I'd be happy to create a PR with that if you'd like?

**Comment by stefpiatek** [comment]
Oh this is also very delayed (sorry for bringing it up again @ldko) but I was wondering if you'd be happy to add the `hacktoberfest-accepted` tag for this PR? Making a late attempt to get the 4 PRs
