### ISSUE TITLE
Confusing phrasing of "Check Your Understanding" in episode 1

### ISSUE THREAD

**Issue by ncf0003** [swcarpentry/python-novice-inflammation#860]
https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/_episodes/01-intro.md
I think the phrasing of the CYU question of the first episode could be improved or perhas the solution changed to better reflect the question. Presently the prompt is:

"What values do the variables mass and age have **after each statement** in the following program? Test your **answers** by executing the commands."

However, the solution only reflects a single answer which is the output of the print statement at the end of the little program.

**Comment by ldko** [comment]
Hi Nicolas, 
Thanks for submitting this issue! I agree with you that the phrasing of the challenge and the solution don't wholly align. Since the first two lines are variable definitions and the next two lines each only alter one of the variables, perhaps it would suffice to change the prompt to:

```
What values do the variables `mass` and `age` have after the following statements? Test your answer by executing the lines.
```

Would you like to submit a pull request to fix the issue?

**Comment by maxim-belkin** [comment]
Fixed in https://github.com/swcarpentry/python-novice-inflammation/commit/975bbb2b9b8f5fd85919b54ba71056d919d3b74b
