### ISSUE TITLE
Explanation of a list

### ISSUE THREAD

**Issue by mattgillucl** [swcarpentry/python-novice-inflammation#871]
In the episode [Repeating Actions with Loops](https://swcarpentry.github.io/python-novice-inflammation/04-loop/index.html), in the section "Computing the Value of a Polynomial", the text says:

```The built-in function enumerate takes a sequence (e.g. a list)...```

I know this is probably a bit pedantic but, as far as I can tell, the concept of a "list" (in a programming sense) isn't actually explained at (or before) this point. If a participant genuinely hasn't done any programming before, they may wonder what a `list` is, exactly. 

Maybe the section immediately beforehand (about reversing a string such as "Newton") could add a short statement about, say, a string being a list of characters, or something similar?

Just a thought.

**Comment by mattgillucl** [comment]
I just realised the very next episode is all about lists.

Thus a quick fix would be to link to [Storing Multiple Values in Lists](https://swcarpentry.github.io/python-novice-inflammation/05-lists/index.html) from the word `list` in the text `(e.g. a list)`.

**Comment by ldko** [comment]
Hi @mattgillucl , thanks for pointing out this inconsistency in the lesson. There has been some work around [moving the `list` episode before the `loop` episode](https://github.com/swcarpentry/python-novice-inflammation/issues/496), but since `list` isn't yet taught where this exercise appears, perhaps the exercise should move to the `list` episode exercises. Another option is to change the exercise, so it teaches `enumerate` with the sequence being a string. The suggestion by @mattgillucl to link to the `list` episode for context seems like a reasonable option if we want to keep the exercise as-is where it is... Do you all have preferences about this @maxim-belkin @annefou ?

**Comment by maxim-belkin** [comment]
I think adding a (forward-)reference￼ is a good idea￼ in this case. 👍

**Comment by ldko** [comment]
@mattgillucl regarding 
> Thus a quick fix would be to link to Storing Multiple Values in Lists from the word list in the text (e.g. a list).

Would you be willing to open a PR to add the link?

**Comment by mattgillucl** [comment]
Hi people. Sorry for not responding earlier but for some reason I haven't been receiving notifications.

OK I will have a quick look and hopefully do a PR.

**Comment by mattgillucl** [comment]
Can someone give me write permission on the repo please?

    python-novice-inflammation git:(mattgillucl-lists-fix) git push --set-upstream origin mattgillucl-lists-fix
    remote: Permission to swcarpentry/python-novice-inflammation.git denied to mattgillucl.
    fatal: unable to access 'https://github.com/swcarpentry/python-novice-inflammation.git/': The requested URL returned   error: 403

**Comment by maxim-belkin** [comment]
You'd have to fork this repo, make changes in your fork, and then submit a pull request to this repo.
Please see https://guides.github.com/activities/forking/ for more info but please let us know if you need help along the way.

**Comment by mattgillucl** [comment]
Sorry, I forgot about having to fork.

I have made a PR https://github.com/swcarpentry/python-novice-inflammation/pull/873

I hope that fixes it.
