### ISSUE TITLE
Type/dtype in episodes 1 and 2

### ISSUE THREAD

**Issue by nrush** [swcarpentry/python-novice-inflammation#899]
My recommendation is to provide slightly more details on data types in the first episode to better flow into the dtypes function in the second. The way episode 2 flows, when dtypes is mentioned, it reads as if the students are already familiar with the type() function. By briefly showing how the type() function can be called to show whether variables are integers, strings, ect., it can give students a bit more understanding as to why calling type() on a numpy array wouldn't work to reveal the types of the numbers inside. I believe this can be done in less than a minute in the first episode when you're already teaching about the variable types. One could also briefly discuss casting variables to other types using int(), str(), ect., but I'm not sure that's fully necessary.

**Comment by ldko** [comment]
Hi Nathaniel,
Thank you for taking the time to open this issue. I think it makes sense to introduce `type()` in the _Types of Data_ section of the [first episode](https://swcarpentry.github.io/python-novice-inflammation/01-intro/index.html). It is something we have been meaning to add as mentioned in PR #766. Regarding type casting, we have not included it at this point, since we aren't making use of it in the lesson and inflammation story line and must keep from adding too much content for a workshop setting. Do you want to make a PR to introduce the `type()` function?

**Comment by ldko** [comment]
This was addressed in #931.
