### ISSUE TITLE
Understanding the Inflammation Data

### ISSUE THREAD

**Issue by jack89roberts** [swcarpentry/python-novice-inflammation#909]
This is very much related to #887 and #179.

I'm reading through the material for the first time and there are a couple of places where I'm slightly confused/unclear about the contents of the inflammation dataset (and how I'd explain it when teaching). It would be great to hear thoughts from the community on the following:

**[Episode 3: Visualizing Tabular Data](https://swcarpentry.github.io/python-novice-inflammation/03-matplotlib/index.html)**

> The result is a roughly linear rise and fall, which is suspicious: we might instead expect a sharper rise and slower fall.

Why might we expect a sharp rise and slower fall? I'm not familiar with the context for the dataset or the domain, but if I assume all patients start the new treatment at day 0 I might expect their mean inflammation to stay roughly constant for a while before the treatment starts to take effect and inflammation falls. 

Similarly, there is this comment a bit later in the lesson:

> The maximum value rises and falls smoothly, while the minimum seems to be a step function. Neither trend seems particularly likely, so either there’s a mistake in our calculations or something is wrong with our data.

I can kind of believe these triangular shapes are unlikely in a real dataset, but is there a good way to explain why?

**[Episode 6: Analyzing Data from Multiple Files](https://swcarpentry.github.io/python-novice-inflammation/06-files/index.html)**

We have multiple files but what are they meant to represent? Maybe results from different locations, different age groups, or even different months of the year (since there are 12 of them)?

Also, do all files have the same number of patients? I think that should be known before looking at the mean/min/max values in each file (maybe something that could be added to the data checks in the next episode, but also could be solved by adding a comment that we already know all the files are the same).

Thanks! Happy to submit a PR later with changes based on any comments.

**Comment by maxim-belkin** [comment]
Hi Jack.

Those are all good questions. Before I share the explanations I came up with when I asked myself the same questions, I have to say that neither I nor other maintainers are married to the dataset used in the lesson and we're open to suggestions to change the dataset and/or the storyline. Note that the script used to generate the dataset is, in fact, provided in the lesson repository: [permalink](https://github.com/swcarpentry/python-novice-inflammation/blob/eb0dea7cc041845304be218a5d7eda9b4ca5a3a7/code/gen_inflammation.py).

> Why might we expect a sharp rise and slower fall?

I'm not in any way connected to the area of arthritis treatment. I can imagine, though, that in treatment trials data is sent to a third-party to confirm validity of claims of treatment developers. So, the data we have here could be capturing a few days before patients are given the treatment and a few days after - that would explain the rise and fall. Not sure about linearity but I thought that treatments usually give immediate improvement and then a longer period during which things improve slower.

But here I have to agree with your next concern:

> I'm not familiar with the context for the dataset or the domain, but if I assume all patients start the new treatment at day 0 I might expect their mean inflammation to stay roughly constant for a while before the treatment starts to take effect and inflammation falls.

I agree that that if patients had arthritis in the first place, the number of inflammation bouts shouldn't start at 0 but fluctuate around some number and then start decaying.

> I can kind of believe these triangular shapes are unlikely in a real dataset, but is there a good way to explain why?

In general - 🤷🏻 . To me, the most suspicious part is that these steps are regular (overall, 2 linear dependencies) -- I'm not concerned with step-wise nature of the dependencies because # of minimum and maximum inflammation bouts can only be integer, after all.

> We have multiple files but what are they meant to represent? Maybe results from different locations, different age groups, or even different months of the year (since there are 12 of them)?
>
> Also, do all files have the same number of patients? I think that should be known before looking at the mean/min/max values in each file (maybe something that could be added to the data checks in the next episode, but also could be solved by adding a comment that we already know all the files are the same).

All good ideas and questions. Tying back to my first explanation -- we wouldn't know if we're the third-party evaluating the effectiveness of that treatment. But, of course, if we're the party that develops, applies, and checks the effectiveness of the treatment, then we should know all of that.

I think we should discuss which storyline makes the most sense and make appropriate changes to the script(s), images, and the lesson.

Thanks for bringing this up, Jack!

**Comment by jack89roberts** [comment]
Great, thanks for the reply! I hadn't realised the dataset is generated for the lesson, that gives us scope to tweak things to fit a narrative if needed I suppose. It definitely would be nice to have a clear storyline for everything.

**Comment by mike-ivs** [comment]
Hi Jack,

Just wondering if you ever got round to looking at the storyline/other datasets?

I just gave an abridged version of the lesson, focused around the research narrative and how you can quickly dive into a CSV of data without that much effort in Python, and thus "invented" a bit more of a narrative around the dataset, expected trends, etc. (disclaimer: I'm certainly not an expert in arthritis treatment either!)

I was contemplating putting in a PR as I had the exact same thoughts as you (and  #887 and #179) when it case to the trends and context of the dataset, but I didn't want to step on any toes if you had already worked on a narrative or on changing datasets.

**Comment by jack89roberts** [comment]
Hi @mike-ivs , no I haven't unfortunately so that sounds great!
