### ISSUE TITLE
Add introduction to built-in functions in 'Repeating Actions with Loops' 

### ISSUE THREAD

**Issue by Columoleary** [swcarpentry/python-novice-inflammation#919]
Hello Team,

I was reading through the [Repeating Actions with Loops](https://swcarpentry.github.io/python-novice-inflammation/04-loop/index.html) episode and noticed that the built-in loop functions `len` and `range` are introduced without providing an introduction to built-in loop functions. In this episode, `len` is introduced in a sentence between two code snippets:

"Note also that finding the length of a string is such a common operation that Python actually has a built-in function to do it called `len`:"

After this subsection, the function `range` is introduced.

May I suggest introducing special functions with a couple of sentences. For example: "Built-in functions: Python contains several built-in functions which can be used instead of for loops in certain situations...". Then the functions `len` and `range` can be introduced, and demonstrated using the pre-existing examples in the lesson. `len` and `range` are already side-by-side in the lesson, so I do not think this suggested change will alter the flow of the lesson, and it might provide more clarity for the learner. 

I hope this helps!

Thanks,
Colum

**Comment by ldko** [comment]
Hello @Columoleary ,
Thank you for opening an issue about built-in functions. It looks like we mention "built-in" in the loop, files, conditionals, and functions episodes of the lessons, but as you point out with the loops episode, we never introduce what built-in functions are. Rather than specifically introducing built-in functions in the context of loops, I suggest more generally introducing built-in functions briefly in the first episode when we first use the `print` function. Perhaps we could make use of how functions are defined in the functions episode "‘functions’ — a shorthand way of re-executing longer pieces of code" and mention that they have a name and parentheses and that we'll see more example and learn how to create them as we progress through the lesson. What you think, Colum @maxim-belkin ?

**Comment by maxim-belkin** [comment]
I like the suggestion to introduce built-in Python functions more generally. Even knowing the term "builtin" (or built-in function) is useful. There are several functions that we can use as examples (`print()`, `len()`, `range()`, `abs()`, `min()`, `max()`, `round()`, `sum()`, `sorted()`, `dir()`... maybe `any()` and `all()`) and the point that we can make is that we didn't have to do anything to use them.

I have to admit I'm not familiar with built-in loop functions in Python (I heard about them in R).

**Comment by Columoleary** [comment]
@ldko I agree, it would be a great idea to introduce built-in functions at the beginning of the lesson, with perhaps a short list of examples in the episode, as @maxim-belkin suggested.

Thank you for your feedback on this!

**Comment by ldko** [comment]
This is addressed by introducing the concept of built-in functions in #931 . Thanks for your input on the topic @Columoleary !
