### ISSUE TITLE
Episode 8 Creating Functions - Mention doctest ?

### ISSUE THREAD

**Issue by chavid** [swcarpentry/python-novice-inflammation#933]
<details>
<summary><strong>Motivate the use of the prompt in the docstring example</strong></summary>
Hi.

The docstring which is shown for function `offset_mean` includes an example, which is fine.

Yet, the format of the example, especially the use of `>>>`, may seem superfluous to a python beginner.
It may be worth to mention that this format will help some tools, such as `doctest`, to automatically check that the example is never broken when one modify the implementation of the function. Testing is a key topic of the episode ;)

There is no need to explicitly say it during the training, and make it longer. But I would just mention it with a short sentence in the text, for students who read again the episode later on.

What do you think ?
</details>

**Comment by ldko** [comment]
Hi @chavid,
This is something worth thinking about.

I think the format including `>>>` likely often doesn't register as meaningful to a beginner and isn't necessarily something we need to call out. I am reluctant to mention `doctest` as it may be distracting, though I get your point that just because it is in the text doesn't mean it needs to be mentioned aloud--sometimes though, I think having extra stuff in the content that isn't intended to be taught during the workshop can be more difficult for instructors who then need to constantly be thinking, should I teach this part?

If having the example with `>>>` in it could be confusing, another option would be to change the longer docstring to not include an example.

However, I am not strongly against just mentioning and linking to `doctest` in the context of `>>>` in the docstring example with no more than the addition of a sentence if others (@maxim-belkin ?) have opinions favoring its mention and someone wants to open a pull request.

Thanks for bringing up the issue @chavid !

**Comment by maxim-belkin** [comment]
That's an interesting suggestion... but considering the context of the episode I'm not too keen on mentioning `doctest` because it would happen right after we introduce docstrings and, therefore, would overwhelm learners with information. 

Speaking of this part of the episode in general -- it looks like apart from the doctest-able docstring, this specific example isn't different from the code block right before it. So it looks like we can remove it altogether.

**Comment by chavid** [comment]
I worked on a merge request, trying to remove this doctest syntax, yet keeping the examples in the docstrings here and there in the episode (because I thik it is a good practice to include examples in docstrings). After searching the way to best include some examples in docstrings... I changed my mind about my initial problem. The use of ">>>" is not that doctest specific. It is the default python interpreter prompt, and surely a good way to introduce an example. So, finally, I would change nothing ;) If student ask abotu this ">>>", we can simply answer that's the usual python prompt, and the usual way to introduce an example.
