### ISSUE TITLE
Analyzing data from multiple files: Wording regarding glob

### ISSUE THREAD

**Issue by codingS3b** [swcarpentry/python-novice-inflammation#937]
[This episode](https://swcarpentry.github.io/python-novice-inflammation/06-files/index.html) introduces the `glob` package using the words "a library with a rather unpleasant name". 
I see two problems with that: 
1) From my point of view this is not a good choice of words since students might be led towards feeling negatively about this very useful set of functions.
2) I think we should use "package" rather than "library" in the python world since otherwise students new to python might get confused when switching between those concepts.

To resolve both issues, the sentence introducing `glob` could be rephrased with a focus more strongly based on what it can be used for, e.g. "a package which provides functionality for filtering files based on their naming scheme".

**Comment by ldko** [comment]
Hi @codingS3b ,
I also don't like introducing `glob` by saying it has a "rather unpleasant name" for the reasoning you give and would be glad to see that wording go.

Regarding "package" vs. "library", I believe `glob` is technically a module in the Python standard library, not a package. Library is a vaguer term, that I think works ok in this context because in this lesson we don't get into the detail of what is a module vs. a package vs. a library, and I think that is ok, since we aren't trying to cover every nuance of Python for novice learners. Since we use library to introduce `numpy` and `matplotlib`, I think it may be less confusing to stick with "library" here.

Would you like to open a pull request to remove the "unpleasant name" description?

**Comment by maxim-belkin** [comment]
Hi Sebastian,  thanks for brining this up! 

I concur with you and Lauren on the first issue -- let's fix that unnecessary wording about `glob`. 

Regarding the choice of the right expression for `glob` (package/module/library): as Lauren explained above, `glob` is, technically, a module (it's a single file) but within the scope of our lesson we don't have an opportunity to explain this part of Python nomenclature (that is, there is no need to know it to achieve our goal(s)). In the end, even if modules were called bagels and packages &mdash; donuts, we still would be importing them with `import bagel` and `import donut`. I guess, what I'm really trying to say is that it's more important for a new learner to remember the `import <name>` syntax than the difference between modules and packages which they can learn more about later.

**Comment by codingS3b** [comment]
Hi @maxim-belkin and @ldko, thanks for your quck response and feedback towards that issue and thanks for bringing the module/package issue up and that it might also cause confusion if introduced too early. I was not aware that `glob` is indeed just a single file!
So I will open a PR and change only the part about glob being unpleasant!

**Comment by maxim-belkin** [comment]
Thanks for submitting the fix, Sebastian!
Thanks for taking care of the PR, Lauren!
Great work!
