### ISSUE TITLE
Copying a list with the list function produces TypeError in Python3

### ISSUE THREAD

**Issue by tcouch** [swcarpentry/python-novice-inflammation#949]
Link to page: https://swcarpentry.github.io/python-novice-inflammation/04-lists/index.html#ch-ch-ch-ch-changes

> If you want variables with mutable values to be independent, you must make a copy of the value when you assign it.
> ```
> salsa = ['peppers', 'onions', 'cilantro', 'tomatoes']
> my_salsa = list(salsa)        # <-- makes a *copy* of the list
> salsa[0] = 'hot peppers'
> print('Ingredients in my salsa:', my_salsa)```
I get the following error with Python3:
```
>>> my_salsa = list(salsa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'list' object is not callable
```
I'd suggest using `my_salsa = salsa.copy()` or `my_salsa = salsa[:]`

**Comment by tcouch** [comment]
See also `primes = list(odds)` further down the page

**Comment by maxim-belkin** [comment]
> I get the following error with Python3:
> 
> ```
> >>> my_salsa = list(salsa)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: 'list' object is not callable
> ```

This error means that somewhere in the code you created a variable called `list` and assigned it to some list, for example:
```
list = [1, 2, 3]
```
When you later do `list(salsa)`, Python thinks that `list` is a variable called `list` and not the built-in function, so it doesn't know how to proceed. To fix this, you'd have to delete this variable: `del list`.

`list` is an example of a name that we can use as a variable name but, probably, should not because it overrides the built-in Python function.

related to: #834 and #663 (for variable names)

**Comment by tcouch** [comment]
Oh dear, boy is my face red. Yeah, I was using an old python session from yesterday. Sorry about that and thanks for the patient explanation @maxim-belkin

**Comment by maxim-belkin** [comment]
No worries! It was a good debugging exercise: the `'list' object is not callable` message means that an object of type `list` was called as a function (i.e., with parentheses right after it). The first line in the traceback (`my_salsa = list(salsa)`) has only one "function call" -- `list(salsa)`. Connecting dots together: the `list` in `list(salsa)` is actually a Python list, and not what one may expect it to be.
